apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: microservices
type: Opaque
data:
  username: cm9vdA==  # 'root' in base64
  password: ZXhhbXBsZQ==  # 'example' in base64